YourVoiceHeard/emailreps/urls.py
from django.urls import path

from . import views

app_name = 'emailreps'
urlpatterns = [
    path('', views.index, name='index'),
    #path('emailofficials', views.contact_reps, name='contact_reps'),
    #path('aboutsenators', views.senator_page, name='SenatorPage'),
    #path('aboutreps', views.reps_page, name='RepsPage'),
    path('makeissue', views.make_issue, name='make_issue'),
    path('postissue', views.add_issue, name='post_issue'),
    path('ice', views.ice, name='ice'),
    path('blm', views.blm, name='blm'),
    path('proposeissues', views.proposeissues, name='proposeissues'),
    path('caofficals', views.caofficals, name='caofficals'),
    path('2020elections', views.elections2020, name='2020elections'),
    path('climatechange', views.climatechange, name='climatechange'),
    path('yemen', views.yemen, name='yemen'),
    path('vote', views.vote, name='vote'),
    path('results', views.results, name='results'),
    path('upvote/<int:id>/', views.upvote, name='upvote'),
    path('downvote/<int:id>/', views.downvote, name='downvote'),
    ]

YourVoiceHeard/emailreps/models.py
import datetime

from django.db import models
from django.utils import timezone

class Representative(models.Model):
    rep_name = models.CharField(max_length=200)
    comittee = models.CharField(blank=True, max_length=200)
    website = models.URLField(blank=True,max_length=400)
    state = models.CharField(max_length=50)
    party = models.CharField(blank=True, max_length=20)
    district = models.CharField(blank=True, max_length=10)
    def __str__(self):
        return self.rep_name
    def first_last_name(self):
        return self.rep_name.split(' ', 1)
class Senator(models.Model):
    sen_name = models.CharField(max_length=200)
    website = models.URLField(blank=True,max_length=400)
    state = models.CharField(max_length=50)
    party = models.CharField(blank=True, max_length=20)
    def __str__(self):
        return self.sen_name
    def first_last_name(self):
        return self.rep_name.split(' ', 1)

class Issue(models.Model):
    issue_name = models.CharField(max_length=200)
    issue_text = models.TextField()
    def __str__(self):
        return self.issue_name

class Vote(models.Model):
    vote_type = models.IntegerField()
    ip_address = models.GenericIPAddressField()
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    def __str__(self):
        if self.vote_type == 1:
            return ('Upvote')
        elif self.vote_type == 0:
            return ('Neutral')
        else:
            return ('Downvote')

YourVoiceHeard/emailreps/forms.py
from django import forms
from .models import Issue

class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['issue_name', 'issue_text']
        widgets = {
            'issue_name': forms.TextInput(
            attrs={'id': 'issname', 'class':'input', 'placeholder': 'Name of your issue', 'aria-label' : 'Issue Title'}),
            
            'issue_text': forms.Textarea(
            attrs={'id': 'isstxt', 'class':'input', 'placeholder': 'Enter a relavent political issue we should put resources for on the site.', 'aria-label' : 'Issue Text'})
        }
    

YourVoiceHeard/emailreps/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.db.models import Avg, Count, Min, Sum
from django.db.models.functions import Coalesce
from .models import Senator, Representative, Issue, Vote
from .forms import IssueForm

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

# Index page
def index(request):
    context = {}
    return render(request, 'index.html', context)

# Black Lives Matter Page
def blm(request):
    reps = Representative.objects.all()
    senators = Senator.objects.all()
    context = {'reps': reps, 'sens': senators}
    return render(request, 'blm.html', context)

# Ice Page
def ice(request):
    reps = Representative.objects.all()
    senators = Senator.objects.all()
    context = {'reps': reps, 'sens': senators}
    return render(request, 'ice.html', context)

# Yemen Page
def yemen(request):
    reps = Representative.objects.all()
    senators = Senator.objects.all()
    context = {'reps': reps, 'sens': senators}
    return render(request, 'yemen.html', context)

# Climate Change Page
def climatechange(request):
    reps = Representative.objects.all()
    senators = Senator.objects.all()
    context = {'reps': reps, 'sens': senators}
    return render(request, 'climatechange.html', context)

# Issue proposal page
def proposeissues(request):
    issue_form = IssueForm()
    context = {'issue_form': issue_form}
    return render(request, 'proposeissues.html', context)

# Page that lists the current California Representatives and Senators
def caofficals(request):
    reps = Representative.objects.all()
    senators = Senator.objects.all()
    context = {'reps': reps, 'sens': senators}
    return render(request, 'caofficals.html', context)

# Page with info about the 2020 Elections
def elections2020(request):
    context = {}
    return render(request, '2020elections.html', context)

# Voting redirect
def vote(request):
    context = {}
    return redirect('emailreps:results')

# Processes upvote requests
def upvote(request, id):
    ip = get_client_ip(request)
    issue = Issue.objects.get(id=id)
    if Vote.objects.filter(ip_address=ip, issue=issue).exists():
        vote_check = Vote.objects.get(ip_address=ip, issue=issue)
        
        # If the vote was an upvote, sets it to neutral
        if vote_check.vote_type == 1:
            vote_check.vote_type = 0
        # If the vote was neutral, sets it to an upvote
        elif vote_check.vote_type == 0:
            vote_check.vote_type = 1
        # If the vote was a downvote, sets it to an upvote
        else:
            vote_check.vote_type = 1
        vote_check.save()
        return redirect('emailreps:results')
    # If there was no existing vote, create a vote object tied to the client's IP for this given issue
    else:
        vote = Vote(vote_type=1, ip_address=get_client_ip(request), issue=issue)
        vote.save()
        return redirect('emailreps:results')

# Processes downvote requests
def downvote(request, id):
    ip = get_client_ip(request)
    issue = Issue.objects.get(id=id)
    # Checks if a vote for this IP and Issue exists in the db already
    if Vote.objects.filter(ip_address=ip, issue=issue).exists():
        vote_check = Vote.objects.get(ip_address=ip, issue=issue)

        # If the vote was a downvote, set it to neutral
        if vote_check.vote_type == -1:
            vote_check.vote_type = 0
        # If the vote was neutral, set it to a downvote
        elif vote_check.vote_type == 0:
            vote_check.vote_type = -1
        # If the vote was an upvote, set it to a downvote
        else:
            vote_check.vote_type = -1
        vote_check.save()
        return redirect('emailreps:results')
    # If there was no existing vote, create a vote object tied to the client's IP for this given issue
    else:
        vote = Vote(vote_type=-1, ip_address=get_client_ip(request), issue=issue)
        vote.save()
        return redirect('emailreps:results')

# Results page for issue proposal and voting.
def results(request):
    # Counts the number of vote objects for a given issue, if none exist sets them to 0.
    curr_issues = Issue.objects.annotate(true_vote=Coalesce(Sum('vote__vote_type'), 0)).order_by('-true_vote')
    context = {'issues': curr_issues}
    return render(request, 'results.html', context)

# Pending deletion
def reps_page(request):
    reps = Representative.objects.all()
    context = {'reps': reps}
    return render(request, 'RepsPage.html', context)

# Testing page
def make_issue(request):
    Issue.objects.all().delete()
    issue_form = IssueForm()
    curr_issues = reversed(Issue.objects.all())
    context = {'issue_form': issue_form, 'issues': curr_issues}
    return render(request, 'make_issue.html', context)

# Post request to add the issue to the DB
@require_POST
def add_issue(request):
    form = IssueForm(request.POST)
    if form.is_valid():
        new_issue = form.save()
    return redirect('emailreps:results')

YourVoiceHeard/emailreps/templates/ice.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Site Metas -->
    <title>Your Voice Heard - ICE</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="#" type="image/x-icon" />
    <link rel="apple-touch-icon" href="#" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}" />
    <!-- Pogo Slider CSS -->
    <link rel="stylesheet" href="{% static 'website/css/pogo-slider.min.css' %}" />
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'website/css/responsive.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'website/css/custom.css' %}" />

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="inner_page" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

    <!-- LOADER -->
    <div id="preloader">
        <div class="loader">
            <img src="{% static 'website/images/loader.gif' %}" alt="#" />
        </div>
    </div>
    <!-- end loader -->
    <!-- END LOADER -->

   <!-- Start header -->
    <header class="top-header">
        <div class="header_top">

            <div class="container">
                <div class="row">
                    <div class="logo_section">
                        <a class="navbar-brand" href="{% url 'emailreps:index' %}"><img src="{% static 'website/images/logo.jpg' %}" alt="image"></a>
                    </div>
                    <div class="site_information">
                        <ul>
                            <li><a href="mailto:yourvoiceheard115@gmail.com"><img src="{% static 'website/images/mail_icon.png' %}" alt="#" />yourvoiceheard115@gmail.com</a></li>
                            <li><a href="tel:yourvoiceheard115@gmail.com"><img src="{% static 'website/images/phone_icon.png' %}" alt="#" />N/A</a></li>
                            <li><a class="join_bt" href="{% url 'emailreps:vote' %}">We need your voice</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <div class="header_bottom">
          <div class="container">
            <div class="col-sm-12">
                <div class="menu_orange_section">
                   <nav class="navbar header-nav navbar-expand-lg">
                     <div class="menu_section">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                    <ul class="navbar-nav">
                        <li><a class="nav-link active" href="{% url 'emailreps:index' %}">Home</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:blm' %}">#BLM</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:ice' %}">ICE</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:yemen' %}">Yemen</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:climatechange' %}">Climate Change</a></li>
                         <li><a class="nav-link" href="{% url 'emailreps:2020elections' %}">2020 Elections</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:caofficals' %}">About CA Officals</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:proposeissues' %}">Propose Your Issues?</a></li>
                    </ul>
                </div>
                     </div>
                 </nav>
                </div>
            </div>
          </div>
        </div>

    </header>
    <!-- End header -->

    <!-- Start Banner -->
    <div class="section inner_page_banner">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="banner_title">
                        <h3>ICE</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Banner -->

    <!-- section -->
    <div class="section layout_padding about_bg">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="full paddding_left_15">
                        <div class="heading_main text_align_left">
                           <h2>About</h2>
                        </div>
                    </div>
                    <div class="full paddding_left_15">
                        <p id="source-text" class="text-light"> Abolish ICE is a political movement that proposes abolition of the U.S. Immigration and Customs Enforcement (ICE). The movement gained traction in June 2018, due to controversy of the Trump administration family separation policy. </p>
                    </div>
                    <div class="full paddding_left_15">
                        <a class="main_bt" href="https://en.wikipedia.org/wiki/Abolish_ICE">Read More ></a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="full text_align_right_img">
                        <img src="{% static 'website/images/img3.png' %}" alt="#" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end section -->

    <!-- section -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="full text_align_right_img">
                        <img src="{% static 'website/images/blmindex.jpg' %}" alt="#" />
                    </div>
                </div>
                <div class="col-md-6 layout_padding">
                    <div class="full paddding_left_15">
                        <div class="heading_main text_align_left">
						   <h2><span class="theme_color">Please</span> Send A Message</h2>
                        </div>
                    </div>
                    <div class="full paddding_left_15">
                        <p class="text-light">Please send a message to let your voice be heard.</p>
                    </div>
                    <div class="full paddding_left_15">
                        <a class="main_bt" href="#">About more ></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<!-- end section -->

    <!-- section -->
    <div class="section white_fonts" style="background: #111;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 layout_padding">
                    <div class="full paddding_left_15">
                        <div class="heading_main text_align_left">
                           <h2>Your Message</h2>    
                        </div>
                    </div>
                    <div class="field">
                        <textarea id ="message" name="message" rows="12" cols="50"></textarea>
                    </div>
                </div>
                <div class="col-md-6 layout_padding">
                    <div class="full paddding_left_15">
                        <div class="heading_main text_align_left">
                           <h2>Generate Your Message</h2>    
                        </div>
                    </div>
                    <div class="col-lg-9 col-sm-18">
                    <div class="full">
                        <form class="contact_form_inner" id="messageForm01" action="#">
                            <fieldset>
                                <div class="field">
                                    <input type="text" name="inputFirstName_01" placeholder="First Name" required />
                                </div>
                                <div class="field">
                                    <input type="text" name="inputLastName_01" placeholder="Last Name" required />
                                </div>
								<div class="field">
									<select id ="reps_select" name="reps_select">
										<option value="disabledSelect" disabled selected>Your California Officials</option>
										<optgroup label = "Senators">
											{% for sen in sens %}
												<option value="{{sen.sen_name}}">{{sen.sen_name}}</option>
											{% endfor %}
										</optgroup>
										<optgroup label = "Representatives">
											{% for rep in reps %}
												<option value="{{rep.rep_name}}">{{rep.rep_name}}</option>
											{% endfor %}
										</optgroup>
									</select>
								</div>
                                <div class="field">
									 <button type="button" onclick="location.href='https://www.usa.gov/elected-officials';">YOUR OFFICIALS</button>
									 <p> </p>
                                     <button type="button" onclick="generateMessage(this.form)">GENERATE</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                    </div>
					</div>
                </div>
            </div>
        </div>
    </div>
    <!-- end section -->
	
    <!-- Start Footer -->
    <footer class="footer-box">
        <div class="container">
            <div class="row">
               <div class="col-md-12 white_fonts">
                    <div class="row">
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <img class="img-responsive" src="{% static 'website/images/footer_logo.png' %}" alt="#" />
                            </div>
                        </div>
                        </div>
					</div>
                </div>
			 </div>
        </div>
    </footer>
    <!-- End Footer -->

    <div class="footer_bottom">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <p class="crp">©Created by Students at University of California, Santa Cruz.</p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" id="scroll-to-top" class="hvr-radial-out"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'website/js/jquery.min.js' %}"></script>
	<script src="{% static 'website/js/popper.min.js' %}"></script>
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

    <!-- ALL PLUGINS -->
	<script src="{% static 'website/js/generate-message.js' %}"></script>
    <script src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.pogo-slider.min.js' %}"></script>
    <script src="{% static 'website/js/slider-index.js' %}"></script>
    <script src="{% static 'website/js/smoothscroll.js' %}"></script>
    <script src="{% static 'website/js/form-validator.min.js' %}"></script>
    <script src="{% static 'website/js/contact-form-script.js' %}"></script>
    <script src="{% static 'website/js/isotope.min.js' %}"></script>
    <script src="{% static 'website/js/images-loded.min.js' %}"></script>
    <script src="{% static 'website/js/custom.js' %}"></script>

</body>
</html>

YourVoiceHeard/emailreps/templates/make_issue.html
{% load static %}
<link rel="stylesheet"type="text/css" href="{% static 'CSS/bulma.css' %}">
<div class="container">
<form action="{% url 'emailreps:post_issue' %}" method="POST" role="form">
	{% csrf_token %}
	<div class="field">
		<label for="issname" class="label"> Issue Title </label>
		<div class="control">
		
		{{issue_form.issue_name}}
		</div>
	</div>
	<div class="field">
		<label for="isstxt" class="label"> Issue Title </label>
		<div class="control">
		
		{{issue_form.issue_text}}
		</div>
	</div>
	<button class="button is-link" type="submit">SUBMIT</button>
</form>
</div>

<div class="container">
<div class="tile is-ancestor">
	<div class="tile is-vertical">
		<div class="tile is-parent is-vertical">
		{% for issue in issues %}
			<div class="tile is-child box">
				<p class="title"> {{issue.issue_name}} </p>
				<p class="subtitle"> {{issue.issue_text}} </p>
			</div>
		{% endfor %}
		</div>
	</div>
</div>
</div>




<ul>
	{% for issue in issues %}
		<li> {{issue.issue_name}} </li>
		<ul>
			<li> {{issue.issue_text}} </li>
		</ul>
	{% endfor %}
</ul>

YourVoiceHeard/emailreps/templates/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Site Metas -->
    <title>Your Voice Heard - We Need Your Voice</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="#" type="image/x-icon" />
    <link rel="apple-touch-icon" href="#" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}" />
    <!-- Pogo Slider CSS -->
    <link rel="stylesheet" href="{% static 'website/css/pogo-slider.min.css' %}" />
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'website/css/responsive.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'website/css/custom.css' %}" />

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="inner_page" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

    <!-- LOADER -->
    <div id="preloader">
        <div class="loader">
            <img src="{% static 'website/images/loader.gif' %}" alt="#" />
        </div>
    </div>
    <!-- end loader -->
    <!-- END LOADER -->

   <!-- Start header -->
     <!-- Start header -->
    <header class="top-header">
        <div class="header_top">
            <div class="container">
                <div class="row">
                    <div class="logo_section">
                        <a class="navbar-brand" href="{% url 'emailreps:index' %}"><img src="{% static 'website/images/logo.png' %}" alt="image"></a>
                    </div>
                    <div class="site_information">
                        <ul style = "font-color: ##1f1f1f;">
                            <li><a class="join_bt" href="mailto:yourvoiceheard115@gmail.com">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <div class="header_bottom">
          <div class="container">
            <div class="col-sm-12">
                <div class="menu_orange_section">
                   <nav class="navbar header-nav navbar-expand-lg">
                     <div class="menu_section">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                    <ul class="navbar-nav">
                        <li><a class="nav-link" href="{% url 'emailreps:blm' %}">#BLM</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:yemen' %}">Yemen</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:climatechange' %}">Climate Change</a></li>
                         <li><a class="nav-link" href="{% url 'emailreps:2020elections' %}">2020 Elections</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:caofficals' %}">About CA Officals</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:proposeissues' %}">Propose Issues Relevant to YOU</a></li>
                        <li><a class="nav-link" href="{% url 'emailreps:results' %}">Top Voted Issues</a></li>
                    </ul>
                </div>
                     </div>
                 </nav>
                </div>
            </div>
          </div>
        </div>

    </header>
    <!-- End header -->

    <!-- Start Banner -->
    <div class="section">
        <br><br><br><br><br>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="full">
                        <div class="heading_main text_align_center" style="margin-left: 18%;float: center; position: center; width:100%; display:inline;">
                           <h3>Top Voted Current Issues</h3>
                            <h6 style ="font-size: 20px; font-color: #cc2020;"><i><br>Your Voice Heard hears your opinion. Submit issues our team can generate emails for.</i></h6><br><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- End Banner -->
    <div class="container" style="padding: 15px; border-top: solid 1px #b01c1c; border-bottom: solid 1px #b01c1c">
        <div class="col-md-12">
        <table id="IssueTable" class= "table table-dark" style ="text-align:center;">
            <thead>
                <tr>
                    <th scope="col">Issue Title</th>
                    <th scope="col">Issue Text</th>
                    <th scope="col">Number of Votes</th>
                    <th scope="col">Vote Now!</th>
                </tr>
            </thead>
            <tbody>
            {% for issue in issues %}
                <tr>
                    <td>{{issue.issue_name}} </td>
                    <td>{{issue.issue_text}} </td>
                    <td>{{issue.true_vote}} </td>
                    <td>
                        <a href="{% url 'emailreps:upvote' id=issue.id %}" class='btn btn-dark'> Upvote </a>
                        <a href="{% url 'emailreps:downvote' id=issue.id %}" class='btn btn-dark'> Downvote </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
            </div>
        <br><br>
    </div>

    <!-- Start Footer -->
    <footer class="footer-box">
        <div class="container">
            <div class="row">
               <div class="col-md-12 white_fonts">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            <div class="center_img">
                                <img class="img-responsive" src="{% static 'website/images/footer_logo2.png' %}" alt="#" />
                            </div>
                        </div>
                        </div>
					</div>
                </div>
			 </div>
        </div>
    </footer>
    <!-- End Footer -->

    <div class="footer_bottom">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <p class="crp">©Created by Students at University of California, Santa Cruz.</p>
                </div>
            </div>
        </div>
    </div>

    <a href="#" id="scroll-to-top" class="hvr-radial-out"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'website/js/jquery.min.js' %}"></script>
	<script src="{% static 'website/js/popper.min.js' %}"></script>
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

    <!-- ALL PLUGINS -->
    <script src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.pogo-slider.min.js' %}"></script>
    <script src="{% static 'website/js/slider-index.js' %}"></script>
    <script src="{% static 'website/js/smoothscroll.js' %}"></script>
    <script src="{% static 'website/js/form-validator.min.js' %}"></script>
    <script src="{% static 'website/js/contact-form-script.js' %}"></script>
    <script src="{% static 'website/js/isotope.min.js' %}"></script>
    <script src="{% static 'website/js/images-loded.min.js' %}"></script>
    <script src="{% static 'website/js/custom.js' %}"></script>
<!--
    <script>
        function sortTable() {
        var table, rows, switching, i, x, y, shouldSwitch;
        table = document.getElementById("IssueTable");
        switching = true;
        /*Make a loop that will continue until
        no switching has been done:*/
        while (switching) {
            //start by saying: no switching is done:
            switching = false;
            rows = table.rows;
            /*Loop through all table rows (except the
            first, which contains table headers):*/
            for (i = 1; i < (rows.length - 1); i++) {
            //start by saying there should be no switching:
            shouldSwitch = false;
            /*Get the two elements you want to compare,
            one from current row and one from the next:*/
            x = rows[i].getElementsByTagName("TD")[2];
            y = rows[i + 1].getElementsByTagName("TD")[2];
            //check if the two rows should switch place:
            if (x.innerHTML < y.innerHTML) {
                //if so, mark as a switch and break the loop:
                shouldSwitch = true;
                break;
            }
            }
            if (shouldSwitch) {
            /*If a switch has been marked, make the switch
            and mark that a switch has been done:*/
            rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
            switching = true;
            }
        }
        }
    </script>
-->

</body>
</html>